pipeline {
    agent {
        docker {  // use golang image on docker to do all stages in this pipeline
            image 'golang:1.19.11'
            }
    }
    stages{
        stage("Format and Test"){
            steps{
                sh """
                    echo "Format and Test Stage"
                    export GOCACHE="${WORKSPACE}" # make gocache workspace not /.cache
                    pwd
                    make format
                    make test
                """
            }
        }
        stage("Run"){
            steps{
                sh """
                    echo "Run Stage"
                    export GOCACHE="${WORKSPACE}" 
                    make run
                """
            }
        }
        stage("Build"){
            steps{
                sh """
                    echo "Build Stage"
                    export GOCACHE="${WORKSPACE}" 
                    make build
                    make run_binary
                    make rm
                """
            }
        }
    }
}
