pipeline {

    agent {
        docker {  // use golang image on docker to do all stages in this pipeline
            image 'golang:1.19.11'
            }
    }

    stages{
        stage("Format and Test"){
            steps{
                sh """
                    export GOCACHE="${WORKSPACE}" 
                    pwd
                    ls -l
                    make format
                    make test
                """
            }
        }
    }
}
