pipeline {

    agent {
        docker {  // use golang image on docker to do all stages in this pipeline
            image 'golang:1.19.11'
            }
    }

    stages{
        stage("Format and Test"){
            steps{
                    sh "pwd"
                    sh "ls -l"
                    sh "make format"
                    sh "make test"
            }
        }
        stage("Run"){
            steps{
                    sh "make run"
            }
        }
        stage("Build"){
            steps{
                    sh "make build"
                    sh "make run_binary"
                    sh "make rm"
            }
        }
    }
}
